# Generated by Django 3.2.8 on 2021-10-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=2550)),
                ('author', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('review', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('in_stock', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('number_of_pages', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
                ('year_published', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
